// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// forceScheme
arma::mat forceScheme(arma::mat p, arma::mat dmat, int max_it, double tol, double EPSILON, double fraction);
RcppExport SEXP mp_forceScheme(SEXP pSEXP, SEXP dmatSEXP, SEXP max_itSEXP, SEXP tolSEXP, SEXP EPSILONSEXP, SEXP fractionSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type p(pSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type dmat(dmatSEXP );
        Rcpp::traits::input_parameter< int >::type max_it(max_itSEXP );
        Rcpp::traits::input_parameter< double >::type tol(tolSEXP );
        Rcpp::traits::input_parameter< double >::type EPSILON(EPSILONSEXP );
        Rcpp::traits::input_parameter< double >::type fraction(fractionSEXP );
        arma::mat __result = forceScheme(p, dmat, max_it, tol, EPSILON, fraction);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// lamp
arma::mat lamp(arma::mat X, arma::uvec sampleIndices, arma::mat Ys);
RcppExport SEXP mp_lamp(SEXP XSEXP, SEXP sampleIndicesSEXP, SEXP YsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP );
        Rcpp::traits::input_parameter< arma::uvec >::type sampleIndices(sampleIndicesSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type Ys(YsSEXP );
        arma::mat __result = lamp(X, sampleIndices, Ys);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// tSNE
arma::mat tSNE(arma::mat X, arma::mat Y, double perplexity, arma::uword k, arma::uword niter);
RcppExport SEXP mp_tSNE(SEXP XSEXP, SEXP YSEXP, SEXP perplexitySEXP, SEXP kSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP );
        Rcpp::traits::input_parameter< double >::type perplexity(perplexitySEXP );
        Rcpp::traits::input_parameter< arma::uword >::type k(kSEXP );
        Rcpp::traits::input_parameter< arma::uword >::type niter(niterSEXP );
        arma::mat __result = tSNE(X, Y, perplexity, k, niter);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
